# 1. Base image with Python
FROM python:3.11-slim

# 2. Set workdir
WORKDIR /app

# 3. Copy requirements file
COPY requirement.txt .

# 4. Install dependencies
RUN pip install --no-cache-dir -r requirement.txt

# 5. Copy source code
COPY . .

# 6. Expose FastAPI port
EXPOSE 8002

# 7. Run FastAPI with Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]
